"""fix verification_code type and add verification_code_expiry

Revision ID: 4d4fdd46647d
Revises: 837526e33103
Create Date: 2026-01-14 11:18:56.892911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d4fdd46647d'
down_revision: Union[str, Sequence[str], None] = '837526e33103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code_expiry', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'verification_code',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_code',
               existing_type=sa.String(length=6),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('users', 'verification_code_expiry')
    # ### end Alembic commands ###
